### ISSUE TITLE
[hidden] value can't translatable

### ISSUE THREAD

**Issue by tolgaaaltas** [dotronglong/flarum-hide-me#1]
Hello, i really love your extension thank your for your effort. I translated to Turkish this extension and released in my package. But, if someone marked as anonymous their post, them name shows as [hidden]. Can you make this value translatable? Huge thank you from Turkey, best regards.

**Comment by dotronglong** [comment]
@tolgaaaltas sorry for not replying you in timely manner, I didn't notice to this github notification. Please upgrade to `v0.0.4` and please backup and run migration before using.

You can change text `[hidden]` by translating value of `dotronglong-hide-me.anonymous.username`

**Comment by tolgaaaltas** [comment]
Thank you.
