### ISSUE TITLE
Crash on install: Table 'flarum.flaanonymous_group' doesn't exist

### ISSUE THREAD

**Issue by protostork** [dotronglong/flarum-hide-me#3]
Hi, this extension looks really interesting but either my install is in a broken state or for some other reason it is not creating the right tables and and users. Whenever I enable the extension from the admin area, it crashes the application and throws up the below error message, suggesting that the install script has not created the right tables. Until I either 'composer remove' or manually remove it from the enabled extensions in the settings table, the site doesn't work.

Have you come across this by any chance or could you share an SQL queries or the table schema by any chance that might put the tables into the correct state that the extension expects (and hopefully make it work)?

I'm on 0.1.0 beta 13, and my Flarum table prefix is 'fla'.

`Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'flarum.flaanonymous_group' doesn't exist (SQL: select `flagroups`.*, `flaanonymous_group`.`anonymous_id` as `pivot_anonymous_id`, `flaanonymous_group`.`group_id` as `pivot_group_id` from `flagroups` inner join `flaanonymous_group` on `flagroups`.`id` = `flaanonymous_group`.`group_id` where `flaanonymous_group`.`anonymous_id` = -1)
Previous exceptions
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'flarum.flaanonymous_group' doesn't exist (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'flarum.flaanonymous_group' doesn't exist (42S02)`

**Comment by protostork** [comment]
Hi @dotronglong, I have tried a clean install of Flarum and there it seems to work. Something must have borked the install or database the first time around, or maybe there was a conflict with another extension. It now seems to be do everything as advertised, wonderful work, thank you!

By the way, I saw you removed the Ghost Mode in some of your commits? It seemed like a nice idea, but I assume it was a bit buggy with Flarum's core?

**Comment by protostork** [comment]
I think I've found the culprit: when enabling the FoF Spamblock extension ( https://github.com/FriendsOfFlarum/spamblock ) and when Hide-me is installed (or vice versa), it causes the above error... 
Update: The same thing happens when both hide-me and dem13n/nickname-changer are enabled at the same time. Very strange...

**Comment by metastork** [comment]
I had also posted the issue to the FriendsOfFlarum spamblock extension team, and they weren't sure what was wrong but suggested it looked like something in hide-me that seemed to be breaking things in rare cases. 

Unfortunately I'm not familiar enough with the Flarum framework to make useful suggestions or attempt a fix, but I have shared a full stack trace of the error I'm getting there, maybe it can help pinpointing the issue in case you are interested in a fix and if it's easy to do: https://github.com/FriendsOfFlarum/spamblock/issues/5

**Comment by protostork** [comment]
I had also posted the issue to the FriendsOfFlarum spamblock extension team, and they weren't sure what was wrong but suggested it looked like something in hide-me that seemed to be breaking things in rare cases. 

Unfortunately I'm not familiar enough with the Flarum framework to make useful suggestions or attempt a fix, but I have shared a full stack trace of the error I'm getting there, maybe it can help pinpointing the issue in case you are interested in a fix and if it's easy to do: https://github.com/FriendsOfFlarum/spamblock/issues/5

**Comment by dotronglong** [comment]
@metastork I am really sorry that I didn't notice about github's notifications these days to see your open issue, I created this plugin to enhance privacy for my personal forum, however, since this plugin can be used by other members of flarum as well, it cannot be customised so deeply in order to work with flarum core (and its requirements). Hence, I have to say that I can not support you in this case due to my limited time and the conflict between one or two plugins need much time on investigation. In conclusion, please use with care and I suggest you to fork it and customise it for your own interest. Last but not least, I am appreciate if you can contribute in this plugin.
